export const SET_TARGET_SECTION = "SET_TARGET_SECTION";
export const SET_DOT_CLICK = "SET_DOT_CLICK";
export const RESET_TARGET_SECTION = "RESET_TARGET_SECTION";
export const RESET_DOT_CLICK = "RESET_DOT_CLICK";
