export const LOADING_FEATURES = "LOADING_FEATURES";
export const TOGGLE_IS_LOADING_FEATURES = "TOGGLE_IS_LOADING_FEATURES";
export const ADD_NEW_FEATURE = "ADD_NEW_FEATURE";
export const UPDATE_FEATURE = "UPDATE_FEATURE";
