export const LOADING_REVIEWS = "LOADING_REVIEWS";
export const TOGGLE_IS_LOADING_REVIEWS = "TOGGLE_IS_LOADING_REVIEWS";
export const ADD_NEW_REVIEW = "ADD_NEW_REVIEW";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
