export const LOADING_PACKAGES = "LOADING_PACKAGES";
export const TOGGLE_IS_LOADING_PACKAGES = "TOGGLE_IS_LOADING_PACKAGES";
export const ADD_PACKAGES = "ADD_PACKAGE";
export const UPDATE_PACKAGES = "UPDATE_PACKAGE";
