export const LOAD_SOCIAL_NETWORKS = "LOAD_SOCIAL_NETWORKS";
export const ADD_NEW_SOCIAL_NETWORKS = "ADD_NEW_SOCIAL_NETWORKS";
export const UPDATE_SOCIAL_NETWORKS = "UPDATE_SOCIAL_NETWORKS";
export const SOCIAL_NETWORKS_LOADING = "SOCIAL_NETWORKS_LOADING";

